---
- name: Setup InfluxDB and Grafana
  hosts: grafana_influxdb
  become: yes
  vars:
    influxdb_host: "localhost"
    influxdb_port: 8086
    influxdb_database: "k6"
    grafana_version: "8.0.6"

  tasks:
    - name: Install InfluxDB
      apt:
        name: influxdb
        state: present

    - name: Start and enable InfluxDB service
      systemd:
        name: influxdb
        state: started
        enabled: yes

    - name: Create k6 database in InfluxDB
      influxdb_database:
        hostname: "{{ influxdb_host }}"
        database_name: "{{ influxdb_database }}"
        state: present

    - name: Install Grafana
      apt:
        name: grafana
        state: present
        update_cache: yes

    - name: Start and enable Grafana service
      systemd:
        name: grafana-server
        state: started
        enabled: yes

    - name: Add InfluxDB datasource to Grafana
      uri:
        url: "http://localhost:3000/api/datasources"
        method: POST
        user: "admin"
        password: "admin"
        body_format: json
        body:
          name: "InfluxDB"
          type: "influxdb"
          access: "proxy"
          url: "http://{{ influxdb_host }}:{{ influxdb_port }}"
          database: "{{ influxdb_database }}"
          isDefault: true


#ansible-playbook -i hosts.ini grafana_influxdb_setup.yml
