---
- name: Install k6 and run tests
  hosts: machines  # Replace with your target host group or hostname
  become: yes  # Run tasks with root privileges

  tasks:
    - name: Update apt packages cache
      apt:
        update_cache: yes

    - name: Install prerequisites
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - gnupg

    - name: Install k6
      apt:
        name: k6
        state: present

    - name: Copy k6 test script to instance
      ansible.builtin.copy:
        src: path/to/your-test-script.js  # Replace with your k6 test script path
        dest: /home/ubuntu/your-test-script.js  # Adjust destination path as needed
        mode: 0755  # Ensure script has executable permissions

    - name: Copy split CSV data to instance (part 1)
      ansible.builtin.copy:
        src: path/to/data_part1.csv  # Replace with your data part 1 CSV path
        dest: /home/ubuntu/combined.csv  # Adjust destination path as needed

    - name: Copy split CSV data to instance (part 2)
      ansible.builtin.copy:
        src: path/to/data_part2.csv  # Replace with your data part 2 CSV path
        dest: /home/ubuntu/combined.csv  # Adjust destination path as needed

    - name: Run k6 test and save output to JSON file
      ansible.builtin.shell:
        cmd: k6 run /home/ubuntu/your-test-script.js --out influxdb=http://54.165.250.213:8086/
      register: k6_output
