---
- name: Install k6 and run tests
  hosts: machines
  become: yes

  tasks:
    - name: Update apt packages cache
      apt:
        update_cache: yes

    - name: Install prerequisites
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - gnupg

    - name: Add k6 repository
      apt_repository:
        repo: deb https://dl.k6.io/deb stable main
        state: present
        filename: k6

    - name: Install k6
      apt:
        name: k6
        state: present

    - name: Copy k6 test script to instance
      ansible.builtin.copy:
        src: your-test-script.js
        dest: /home/ubuntu/your-test-script.js

    - name: Copy split CSV data to instance (part 1)
      ansible.builtin.copy:
        src: data_part1.csv
        dest: /home/ubuntu/combined.csv

    - name: Copy split CSV data to instance (part 2)
      ansible.builtin.copy:
        src: data_part2.csv
        dest: /home/ubuntu/combined.csv

    - name: Run k6 test on first segment and save output to JSON file
      ansible.builtin.shell:
        cmd: k6 run --execution-segment "0:1/2" --execution-segment-sequence "0,1/2,1" /home/ubuntu/your-test-script.js --out json=/home/ubuntu/k6_report.json
      register: k6_output
      when: inventory_hostname == 'machine1'

    - name: Run k6 test on second segment and save output to JSON file
      ansible.builtin.shell:
        cmd: k6 run --execution-segment "1/2:1" --execution-segment-sequence "0,1/2,1" /home/ubuntu/your-test-script.js --out json=/home/ubuntu/k6_report.json
      register: k6_output
      when: inventory_hostname == 'machine2'
