---
- name: Install k6 and run tests
  hosts: machines
  become: yes

  tasks:
    - name: Update apt packages cache
      apt:
        update_cache: yes

    - name: Install prerequisites
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - gnupg

    - name: Copy k6 test script to instance
      ansible.builtin.copy:
        src: your-test-script.js
        dest: /home/ubuntu/your-test-script.js

    - name: Copy split CSV data to instance (part 1)
      ansible.builtin.copy:
        src: data_part1.csv
        dest: /home/ubuntu/data_part1.csv

    - name: Copy split CSV data to instance (part 2)
      ansible.builtin.copy:
        src: data_part2.csv
        dest: /home/ubuntu/data_part2.csv

    - name: Run k6 test on first segment and save output to JSON file (machine1)
      ansible.builtin.shell:
        cmd: k6 run --execution-segment "0:1/2" --execution-segment-sequence "0,1/2,1" /home/ubuntu/your-test-script.js --out json=/home/ubuntu/k6_report.json
      register: k6_output
      when: inventory_hostname == 'machine1'

    - name: Run k6 test on second segment and save output to JSON file (machine2)
      ansible.builtin.shell:
        cmd: k6 run --execution-segment "1/2:1" --execution-segment-sequence "0,1/2,1" /home/ubuntu/your-test-script.js --out json=/home/ubuntu/k6_report.json
      register: k6_output
      when: inventory_hostname == 'machine2'

    - name: Send k6 results to InfluxDB
      ansible.builtin.shell:
        cmd: k6 run /home/ubuntu/your-test-script.js --out influxdb=http://54.165.250.213:8086/
      register: k6_output
      environment:
        K6_INFLUXDB_OUTPUT: "http://54.165.250.213:8086/"  # Set the InfluxDB URL

    - debug:
        msg: "k6 test results sent to InfluxDB"
      when: k6_output.rc == 0  # Display debug message if the task was successful
